### ISSUE TITLE
Do you need a maintainer?

### ISSUE THREAD

**Issue by jwir3** [surrsurus/atom-rust-doc-viewer#2]
Hello @surrsurus - I came across this package when hunting for some Rust documentation packages in Atom. I see that you aren't maintaining it any longer, and I was wondering if you require a package maintainer? I'm not sure of the process of moving an apm package over to a new owner, but if you're interested, I'd be willing to take over maintenance of this package for you so that it can see new development.

**Comment by surrsurus** [comment]
A package maintainer would be great for this project, I don't use atom as much as I used to and that's mostly why development fell off. I'm also not too sure how to transfer package ownership, but maybe there's something that can be done where you can still publish to the same project on apm?

**Comment by surrsurus** [comment]
Just added you as a collaborator for push access too.

**Comment by jwir3** [comment]
Thanks! I'll close this issue then as it seems resolved.
